vim.opt.nu = true -- Make line numbers default
vim.opt.relativenumber = true -- Set relative numered lines
vim.o.tabstop = 2 -- Insert n spaces for a tab (default: 8)
vim.o.softtabstop = 2 -- Number of spaces that a tab counts for while performing editing operations (default: 0)
vim.o.shiftwidth = 2 -- The number of spaces inserted for each indentation (default: 8)
vim.o.clipboard = "unnamedplus" -- Sync clipboard between OS and Neovim. (default: '')
vim.o.wrap = false -- Display lines as one long line (default: true)
vim.o.linebreak = true -- Companion to wrap, don't split words (default: false)
vim.o.ignorecase = true -- Case-insensitive searching UNLESS \C or capital in search (default: false)
vim.o.smartcase = true -- Smart case (default: false)
vim.o.cursorline = true -- Highlight the current line (default: false)
vim.o.numberwidth = 2 -- Set number column width to 2 (default: 4)
vim.o.autoindent = true -- Copy indent from current line when starting new one (default: true)
